### ISSUE TITLE
Wrong spells cast on high speed cycles

### ISSUE THREAD

**Issue by SentriTools** [Freeder1k/Wynncraft-Spell-Caster#8]
Running altersurf spellspam, sometimes mod queues wrong spell to be cast (usually, for me its charge instead of warscream). Usually it happens on beginning of the rotation (even on first spell) so It might not be related to the input amount.

Also, spamming the same spell has similar effect (spammed warscream, and randomly got dashed)

**Comment by Freeder1k** [comment]
Click delays below 100 ms run into reliability issues due to Wynncraft capping CPS at 10. There’s nothing I can do about that.
